version: "3.2"
services:
  zero:
    image: dgraph/dgraph:v22.0.2
    # volumes:
    #   - /tmp/data:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
  alpha:
    image: dgraph/dgraph:v22.0.2
    # volumes:
    #   - /tmp/data:/dgraph
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080 --security whitelist=0.0.0.0/0
    ports:
      - 8080:8080
      - 9080:9080
  ratel:
    image: dgraph/ratel:latest
    ports:
      - 8000:8000